### ISSUE TITLE
Implement padding for images within slider divs

### ISSUE THREAD

**Issue by gjwehnes** [thirstyice/abe-site#127] opened 2015-03-06 20:03 UTC
Need padding to fill up divs in slider so that pannels don't 'peek' up from the bottom into other, smaller pannels being currently displayed. At the same time, inline style for those images can be moved to index.css. 
![untitled](https://cloud.githubusercontent.com/assets/6045608/6535288/189f155a-c401-11e4-99cb-6db20d274b96.png)

**Comment by thirstyice** [comment] 2015-03-06 22:56
Could not replicate: Slides didn't peek

**Comment by kid47** [comment] 2015-03-06 22:58
Replicated several times using chrome. It happened about one in every two times, and peeked up from the bottom as in picture

**Comment by thirstyice** [comment] 2015-03-06 23:07
This issue isn't one of padding, is is a duplicate of #41

**Comment by kid47** [comment] 2015-03-06 23:15
Not quite. This is actually the opposite. Whereas the last issue was because the slider wasn't big enough, this time it's because it's too big. Probably related to the same issue, but require different patches from us unless we actually fix the code that's causing the problem

**Comment by thirstyice** [comment] 2015-03-06 23:59
What commit are you on?

**Comment by kid47** [comment] 2015-03-07 00:03
Oh wait, @gjwehnes hadn't pushed that yet. To be added soon I guess

**Comment by thirstyice** [comment] 2015-03-07 00:05
What is?

**Comment by kid47** [comment] 2015-03-07 00:08
The stuff in the picture, which is different slider content. I was there today, however and we fixed it so that it won't go live. Whether the glitchy version will end up on github, I'm not too sure, but I do know that it's cause by images of different sizes in different panels

**Comment by thirstyice** [comment] 2015-03-07 00:14
So putting volleyball (and other sports) back in the slider?

**Comment by kid47** [comment] 2015-03-07 00:22
Never mind. This was an in between commit that we were testing. Not all the athletics panels were removed

**Comment by thirstyice** [comment] 2015-03-07 00:26
Ah

**Comment by thirstyice** [comment] 2015-03-07 00:29
Hopefully that fixes it

**Closed by thirstyice** 2015-03-07 00:29 UTC
Labels: bug, duplicate issue, Interface
